spectaql:
  targetDir: ./docs
  logoFile: ./assets/logo.png
  faviconFile: ./assets/logo.png
  displayAllServers: true
  themeDir: ./docs/custom-theme

introspection:
  removeTrailingPeriodFromDescriptions: false
  schemaFile: ./schemas/*.graphqls
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: ChaosCenter API Documentation
  description: Litmus Portal provides console and UI experience for managing, monitoring, and events around chaos workflows. Chaos workflows consist of a sequence of experiments run together to achieve the objective of introducing some kind of fault into an application or the Kubernetes platform.

servers:
  - url: http://localhost:8080
    description: Dev
  - url: http://localhost:8080/query
    description: Prod
    production: true
